 language: python
 python:
   - "3.6"
 install:
   - pip install -r requirements.txt
 script: python3 -m unittest discover Tests/
 services:
   - docker
 deploy:
   provider: script
   script: bash deploy.sh
   on:
 breanch: master